apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra-cluster.fullname" . }}
  labels:
    {{- include "cassandra-cluster.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9042
      name: cql
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "cassandra-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
