{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra-cluster.fullname" . }}-external
  labels:
    {{- include "cassandra-cluster.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP
      name: cql
  selector:
    app.kubernetes.io/name: {{ include "cassandra-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
