# Default values for react-app.

replicaCount: 2

image:
  repository: gcr.io/eternal-arcana-222507/react-app
  pullPolicy: IfNotPresent
  # The image tag is set via the Jenkins pipeline and updated in values.yaml
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: react-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] # Example: 
  #  - secretName: chart-example-tls
  #    hosts:
  #      - react-app.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
